import { useEffect } from "react";
import { Link } from "react-router-dom";

const LAST_UPDATED = "13 September 2026";
const COMPANY = "Montage Event Management (MA0293072-D)";
const EMAIL = "montage.eventmanagement@gmail.com";
const PHONE = "013-344 6521";

export default function TermsPage() {
  useEffect(() => { window.scrollTo(0, 0); }, []);
  return (
    <div className="min-h-screen bg-[#050508] text-white">
      <div className="max-w-3xl mx-auto px-5 py-16">
        <Link to="/" className="text-neon-cyan text-sm hover:underline mb-8 inline-block">← Back to Montage</Link>
        <h1 className="font-display font-black text-4xl tracking-tighter mb-2">Terms & Conditions</h1>
        <p className="text-white/40 text-sm mb-10">Last updated: {LAST_UPDATED}</p>

        <Prose>
          <p>These Terms and Conditions ("Terms") govern your use of the website montageevents.my and any services provided by {COMPANY} ("Montage", "we", "us"). By making a booking or using our website, you agree to these Terms in full. If you do not agree, please do not use our services.</p>
        </Prose>

        <Section title="1. Our Services">
          <p>Montage provides event services including but not limited to: portable bar and bartending, live BBQ and shisha catering, 360° photobooth rental, sound and lighting rental, inflatable and game rentals, and professional entertainers. Services are delivered at your chosen venue across Shah Alam, Selangor, and the Klang Valley.</p>
        </Section>

        <Section title="2. Bookings">
          <ul>
            <li>All bookings are subject to availability and confirmed only upon receipt of the deposit payment.</li>
            <li>By completing the online booking form, you confirm that the details provided (date, venue, guest count, contact information) are accurate.</li>
            <li>Montage reserves the right to decline any booking at its sole discretion.</li>
            <li>Custom package links generated by our staff are valid for the period stated and are single-use only. Once a deposit is paid, the booking is confirmed.</li>
          </ul>
        </Section>

        <Section title="3. Deposit and Payment">
          <ul>
            <li>A non-refundable deposit of <strong>RM500</strong> is required to secure your booking date. The deposit is payable via ToyyibPay (FPX bank transfer or online banking).</li>
            <li>The remaining balance is due as agreed — typically on the event date or as stated on your invoice (COD terms).</li>
            <li>Payment is to be made to <strong>Montage Event Management — RHB Bank, Account No. 21242400046344</strong>.</li>
            <li>We are not responsible for failed payments caused by issues with your bank or internet connection. Please contact us if you experience payment issues.</li>
          </ul>
        </Section>

        <Section title="4. Cancellation and Refund Policy">
          <p>Please also refer to our full <Link to="/refund-policy" className="text-neon-cyan hover:underline">Refund Policy</Link>.</p>
          <ul>
            <li>The RM500 deposit is <strong>non-refundable</strong> in all circumstances, including if you cancel the event.</li>
            <li>If you cancel more than 14 days before the event: no additional charges beyond the deposit.</li>
            <li>If you cancel within 14 days of the event: 50% of the remaining balance may be charged as a cancellation fee.</li>
            <li>If you cancel within 48 hours of the event: the full package amount is payable.</li>
            <li>Montage reserves the right to cancel your booking in exceptional circumstances (e.g. force majeure, staff emergency). In such cases, we will make every reasonable effort to reschedule. If we cannot, your deposit will be refunded in full — this is the limit of our liability.</li>
          </ul>
        </Section>

        <Section title="5. Event Conduct and Safety">
          <ul>
            <li>You are responsible for ensuring the venue permits our services (e.g. outdoor cooking, audio equipment, inflatables). Montage is not liable for bookings refused entry at the venue.</li>
            <li>For bar services: we comply with applicable Malaysian laws on the service of alcohol. We reserve the right to refuse service to any person who appears intoxicated or is under 21.</li>
            <li>Inflatables and game equipment must be used according to our staff's instructions. You are responsible for the safe supervision of children using inflatable equipment.</li>
            <li>Any damage to our equipment caused by misuse will be charged to you at replacement cost.</li>
            <li>Montage staff reserve the right to cease services immediately if the event environment becomes unsafe or abusive.</li>
          </ul>
        </Section>

        <Section title="6. Liability">
          <ul>
            <li>Montage carries out its services with reasonable skill and care.</li>
            <li>We are not liable for: (a) circumstances beyond our reasonable control (weather, venue access, force majeure); (b) loss or damage not caused by our negligence; (c) indirect or consequential losses.</li>
            <li>Our total liability to you for any claim shall not exceed the amount you paid us for the specific booking.</li>
          </ul>
        </Section>

        <Section title="7. Discount Codes and Promotions">
          <ul>
            <li>Discount codes (including expo game codes) are single-use, non-transferable, and cannot be exchanged for cash.</li>
            <li>Codes are applied to the deposit amount only, subject to the minimum deposit of RM1 (or as stated).</li>
            <li>Montage reserves the right to withdraw or modify any promotion at any time without notice.</li>
          </ul>
        </Section>

        <Section title="8. Photography and Content">
          <ul>
            <li>Our staff and equipment may appear in photos taken at your event. You grant us permission to use event photos/videos for our marketing (Instagram, website) unless you notify us in writing before the event.</li>
            <li>360° photobooth photos are shared with guests via a private link and are stored for up to 30 days before deletion.</li>
          </ul>
        </Section>

        <Section title="9. Intellectual Property">
          <p>All content on montageevents.my (text, design, graphics, logos) is owned by or licensed to Montage Event Management. You may not copy, reproduce, or use any content without our written permission.</p>
        </Section>

        <Section title="10. Website Use">
          <ul>
            <li>You agree not to use our website for any unlawful purpose or in a way that could damage, disable, or impair our services.</li>
            <li>You agree not to attempt to gain unauthorised access to any part of our systems.</li>
            <li>Links to third-party websites are provided for convenience. We are not responsible for the content or practices of third-party sites.</li>
          </ul>
        </Section>

        <Section title="11. Governing Law">
          <p>These Terms are governed by the laws of Malaysia. Any disputes arising from these Terms or your use of our services shall be subject to the exclusive jurisdiction of the courts of Malaysia.</p>
        </Section>

        <Section title="12. Changes to These Terms">
          <p>We may update these Terms from time to time. The current version is always available at montageevents.my/terms. Continued use of our services after any changes constitutes your acceptance of the updated Terms.</p>
        </Section>

        <Section title="13. Contact">
          <p>For any questions about these Terms:<br />
          <strong>{COMPANY}</strong><br />
          Email: <strong>{EMAIL}</strong> · Phone: <strong>{PHONE}</strong></p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div className="mb-8">
      <h2 className="font-bold text-lg text-white mb-3">{title}</h2>
      <Prose>{children}</Prose>
    </div>
  );
}

function Prose({ children }) {
  return <div className="text-white/70 text-sm leading-relaxed space-y-3 [&_strong]:text-white [&_a]:text-neon-cyan [&_a:hover]:underline [&_ul]:list-disc [&_ul]:ml-5 [&_ul]:space-y-1">{children}</div>;
}
